version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./database:/usr/src/app/database
    networks:
      - app-network

networks:
  app-network:
    driver: bridge